version: '3'
services:
  nextjs:
    build: ./
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./:/daydule:cached
      - node_modules:/daydule/node_modules
    ports:
      - '3001:3001'
    command: 'npm run dev'

volumes:
  node_modules:
