name: Sync Fork

# on:
#   schedule:
#     - cron: '*/5 * * * *'
#   workflow_dispatch: # on button click

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: daydule
          base: develop
          head: develop